### ISSUE TITLE
Header/ intro/ footer section

### ISSUE THREAD

**Issue by clee03** [WebDevBootcamp/webspiration#4]
@juliatreiber

**Comment by juliatreiber** [comment]
## Update
- Bootstrap v3.3.4 was downloaded from http://getbootstrap.com/
- Index.html was setup and linked to necessary Bootstrap .CSS and .JS files. 
- Created custom .CSS file and linked in index.html to get header/footer section setup.
- Everything has been pushed to **webspiration** master
- Need to figure out styling with the team to base it on what color scheme/theme we are going for.

**Comment by clee03** [comment]
@juliatreiber completed sticky header/ footer and created content on main/ sub pages
